### ISSUE TITLE
Stuck on bootanimation , with permissive device tree

### ISSUE THREAD

**Issue by Nishant9947** [AospExtended/issue_tracker#3]
Logs Error on stuck :- 

java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions allowlist: {com.android.settings (/system/system_ext/priv-app/Settings): android.permission.RESET_BATTERY_STATS, com.android.systemui (/system/system_ext/priv-app/SystemUI): android.permission.WRITE_APN_SETTINGS, com.android.systemui (/system/system_ext/priv-app/SystemUI): android.permission.PREVENT_POWER_KEY, com.android.launcher3 (/system/system_ext/priv-app/Launcher3QuickStep): android.permission.FORCE_STOP_PACKAGES}

**Comment by sb6596** [comment]
You must have to follow and post your issue according to templates we have

**Comment by Nishant9947** [comment]
I haven't gave all details because i built unofficial for ASUS_X01AD so only i gave only error
with lineage os dt kt vt
